import 'package:flutter/material.dart';

import 'quiz.dart';

List<Quiz> _ = [
     Quiz(
      id: 'q51',
      cid: 'c3',
      level: 1,
      question: '4 x (2 + 3)',
      answers: ['24', '11', '14'],
      rightAnser: '24',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q52',
      cid: 'c3',
      level: 1,
      question: '4 x (2 + 3)',
      answers: ['24', '11', '14'],
      rightAnser: '24',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q53',
      cid: 'c3',
      level: 1,
      question: '4 x (2 + 3)',
      answers: ['24', '11', '14'],
      rightAnser: '24',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q54',
      cid: 'c3',
      level: 1,
      question: '4 x (2 + 3)',
      answers: ['24', '11', '14'],
      rightAnser: '24',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q55',
      cid: 'c3',
      level: 1,
      question: '4 x (2 + 3)',
      answers: ['24', '11', '14'],
      rightAnser: '24',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q56',
      cid: 'c3',
      level: 1,
      question: '4 x (2 + 3)',
      answers: ['24', '11', '14'],
      rightAnser: '24',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q57',
      cid: 'c3',
      level: 1,
      question: '4 x (2 + 3)',
      answers: ['24', '11', '14'],
      rightAnser: '24',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q58',
      cid: 'c3',
      level: 1,
      question: '4 x (2 + 3)',
      answers: ['24', '11', '14'],
      rightAnser: '24',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q59',
      cid: 'c3',
      level: 1,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q60',
      cid: 'c3',
      level: 1,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    // ***************************************************
    // advanced level 2 ------------------------------
    // ***************************************************
    Quiz(
      id: 'q61',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q62',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q63',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q64',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q65',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q66',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q67',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q68',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q69',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q70',
      cid: 'c3',
      level: 2,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    // ***************************************************
    // advanced level 3 ------------------------------
    // ***************************************************
    Quiz(
      id: 'q71',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q72',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q73',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q74',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q75',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q76',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q77',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q78',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q79',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q80',
      cid: 'c3',
      level: 3,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    // ***************************************************
    // advanced level 4 ------------------------------
    // ***************************************************
    Quiz(
      id: 'q81',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q82',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q83',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q34',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q35',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q36',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q37',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q38',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q39',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q40',
      cid: 'c3',
      level: 4,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    // ***************************************************
    // advanced level 5 ------------------------------
    // ***************************************************
    Quiz(
      id: 'q41',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q42',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q43',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q44',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q45',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q46',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q47',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q48',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q49',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
    Quiz(
      id: 'q50',
      cid: 'c3',
      level: 5,
      question: 'adv',
      answers: ['a1', 'a2', 'a3'],
      rightAnser: '36',
      complexity: Complexity.advanced,
    ),
];